# Generated by Django 5.2.5 on 2025-08-14 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fragmento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estratos', models.IntegerField(help_text='Número de estratos do fragmento', verbose_name='Estratos')),
                ('lenhosas', models.IntegerField(help_text='Quantidade de plantas lenhosas', verbose_name='Lenhosas')),
                ('area_basal', models.FloatField(help_text='Área basal do fragmento (m²/ha)', verbose_name='Área Basal')),
                ('altura_esp_dossel', models.FloatField(help_text='Altura específica do dossel (metros)', verbose_name='Altura Específica do Dossel')),
                ('med_ampli_diametros', models.FloatField(help_text='Média da amplitude dos diâmetros (cm)', verbose_name='Média da Amplitude dos Diâmetros')),
                ('dist_diametrica', models.FloatField(help_text='Valor da distribuição diamétrica', verbose_name='Distribuição Diamétrica')),
                ('cresc_dossel', models.CharField(blank=True, choices=[('INICIAL', 'RAPIDO'), ('MEDIO', 'MODERADO'), ('AVANÇADO', 'LENTO')], help_text='Descrição do crescimento do dossel', null=True, verbose_name='Crescimento do Dossel')),
                ('vida_media', models.CharField(blank=True, choices=[('INICIAL', 'CURTA'), ('MEDIO', 'MÉDIA'), ('AVANÇADO', 'LONGA')], help_text='Informações sobre a vida média das espécies', null=True, verbose_name='Vida Média')),
                ('ampli_diametrica', models.CharField(blank=True, choices=[('INICIAL', 'PEQUENA'), ('MEDIO', 'MÉDIA'), ('AVANÇADO', 'GRANDE')], help_text='Descrição da amplitude diamétrica', null=True, verbose_name='Amplitude Diamétrica')),
                ('ampli_altura', models.CharField(blank=True, choices=[('INICIAL', 'PEQUENA'), ('MEDIO', 'MÉDIA'), ('AVANÇADO', 'GRANDE')], help_text='Descrição da amplitude de altura', null=True, verbose_name='Amplitude de Altura')),
                ('epifitas', models.CharField(blank=True, choices=[('INICIAL', 'RARAS'), ('MEDIO', 'POUCAS'), ('AVANÇADO', 'ABUNDANTE')], help_text='Informações sobre epífitas presentes', null=True, verbose_name='Epífitas')),
                ('lianas_herb', models.CharField(blank=True, choices=[('INICIAL', 'ABUNDANTES'), ('MEDIO', 'POUCAS'), ('AVANÇADO', 'RARAS')], help_text='Descrição das lianas herbáceas', null=True, verbose_name='Lianas Herbáceas')),
                ('lianas_lenh', models.CharField(blank=True, choices=[('INICIAL', 'AUSENTE'), ('MEDIO', 'RARA'), ('AVANÇADO', 'PRESENTE')], help_text='Descrição das lianas lenhosas', null=True, verbose_name='Lianas Lenhosas')),
                ('gramineas', models.CharField(blank=True, choices=[('INICIAL', 'ABUNDANTES'), ('MEDIO', 'POUCAS'), ('AVANÇADO', 'RARAS')], help_text='Informações sobre gramíneas presentes', null=True, verbose_name='Gramíneas')),
                ('regen_dossel', models.CharField(blank=True, choices=[('INICIAL', 'AUSENTE'), ('MEDIO', 'POUCA'), ('AVANÇADO', 'INTENSA')], help_text='Descrição da regeneração do dossel', null=True, verbose_name='Regeneração do Dossel')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Fragmento',
                'verbose_name_plural': 'Fragmentos',
                'ordering': ['-created_at'],
            },
        ),
    ]
